---
- name: CONFIGURAR DIRECCIONAMIENTO IPv6 EN LOOPBACK
  hosts: CSR1kv
  gather_facts: false
  connection: local

  tasks:
    - name: ESTABLECER DIRECCION IPv6 EN LOOPBACK 33
      ios_config:
        parents: "interface loopback 33"
        lines:
          - description INTERFAZ LOOPBACK 33 IPv6
          - ipv6 address 3001:ABCD:ABCD:1::1/128
          - ipv6 address FE80::1 link-local